services:
  postgres:
    image: postgres:latest
    container_name: evalart-postgres
    environment:
      POSTGRES_DB: evalart-test-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_backups:/db_backups  


volumes:
  postgres_data:

